#!/usr/bin/env python3

# PROGRAM NAME: Stable Matching (Lab 0)
# CREATED BY: Naz Islam
# DATE: 02/23/2018
# PURPOSE: A script containing a single loop to call gs1.py 
# with different numbe rof suitors
# INPUT(S): It does not take any user input
# OUTPUT(S): fit.log generated by gnuplot and plot the graph


import gs1
import sys
import random
from subprocess import call

def generate_random_number():
    """
    Accepts: It does not take any function arguments
    Returns: A random number of input sizes between 1 and 5500 
    """
    return random.randint(1, 5500)

def generate_random_size():
    """
    Accepts: It does not take any function arguments
    Returns: A random number of iterations between 1 and 20
    """
    return random.randint(1, 20)

def main():
    """
    Accepts: It does not take any function arguments
    Returns: Runs gs1 with different number of input size (1 - 5500), and
    call gnuplot program to perform the fit and plot the graph
    """
    for i in range(generate_random_size()):
        trial_input = generate_random_number()
        gs1.main(trial_input)
    
    call(["/usr/bin/gnuplot", "-persist", "model.gpt"])


if __name__ == '__main__':
    main()

